### ISSUE TITLE
Warning in logs. Will fail in 2023.3

### ISSUE THREAD

**Issue by bckthomas** [SimplySynced/ha-nhl#4]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 09:04:21 (1 occurrences)
Last logged: 09:04:21

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for nhl using this method at custom_components/nhl/__init__.py, line 80: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by ThatTallGuy21** [comment]
This integration is no longer working due to the issue described above and in my post. Below is the log. I was experiencing the same exact issue with the ha-nfl integration until today when they pushed an async fix.

Note: I'm on HA 2023.5.2
- Supervisor 2023.04.1
- Operating System 10.1
- Frontend 20230503.3 - latest

Logger: homeassistant.config_entries
Source: custom_components/nhl/__init__.py:80
Integration: NHL (documentation, issues)
First occurred: 9:34:39 PM (1 occurrences)
Last logged: 9:34:39 PM

Error setting up entry Penguins for nhl
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/nhl/__init__.py", line 80, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by bckthomas** [comment]
You can replace line 80 in __init__.pi

`hass.config_entries.async_setup_platforms(entry, PLATFORMS)`

by

`await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)`

**Comment by ThatTallGuy21** [comment]
That did the trick! Thank you!

**Comment by dexdeadly** [comment]
This has been updated with other fixes as well.
